### ISSUE TITLE
Crop fails when cropper is moved too fast.. 

### ISSUE THREAD

**Issue by KrishnaSharmaCC** [Mawi137/ngx-image-cropper#138] opened 2019-01-22 09:21 UTC
The cropper return no base 64 data if the cropper is moved too fast. This happens when i have set imageBase64 to true and outputType=base64. I have included a demo video showing the bug.
Here is the demo:-

![2019-01-22_13-54-51](https://user-images.githubusercontent.com/42341447/51524719-bdaf9e00-1e54-11e9-8fc8-98a04d328205.gif)
After that i am unable to enlarge the size of cropper too.. So, basically everything stops working.
Any suggestions? @Mawi137

**Comment by Mawi137** [comment] 2019-01-23 19:35
No errors in the console?

**Comment by KrishnaSharmaCC** [comment] 2019-01-24 09:36
@Mawi137  There are no errors in the console too.. It just won't work right we move the cropper too fast (which is very common for mobile devices)

**Comment by Mawi137** [comment] 2019-01-25 17:22
Can you reproduce the error in a StackBlitz? Without an error or example I'm not going to find the problem.

**Comment by Mawi137** [comment] 2019-02-04 19:14
Closing because of no reply in 10 days.

**Closed by Mawi137** 2019-02-04 19:14 UTC
